_docker_compose_setup_commands: &docker_compose_setup_commands
  - cp .env.template .env
  - if [ ! -z "$REQUIRED_MICROSERVICES" ]; then docker-compose up -d $REQUIRED_MICROSERVICES; fi

_docker_compose_build_command: &docker_compose_build_command cd $TRAVIS_BUILD_DIR && for service in $BUILD_SERVICES; do docker-compose build "$service"; done

_python_test_command: &python_test_command cd $COMPONENT_DIR && poetry install -v && poetry run pytest

_python_job_config: &python_job_config
  language: python
  python: "3.8"
  cache:
    pip: true
  install:
    - pip install poetry==1.0.10
  before_script: *docker_compose_setup_commands
  script:
    - *python_test_command
    - *docker_compose_build_command

jobs:
  include:
    - name: schemas
      language: node_js
      node_js: lts/*
      before_install: cd src/schemas

    - name: gui
      language: node_js
      node_js: 14
      before_install:
        - *docker_compose_setup_commands
        - cd src/gui
      script:
        - npm test
        - *docker_compose_build_command
      env:
        - BUILD_SERVICES=gui

    - name: manobase
      <<: *python_job_config
      env:
        - SERVICE_NAME=mano-base
        - COMPONENT_DIR=src/mano-framework/base
        - REQUIRED_MICROSERVICES=broker
        - BUILD_SERVICES=mano-base

    - name: repository
      <<: *python_job_config
      env:
        - SERVICE_NAME=repository
        - COMPONENT_DIR=src/repository
        - BUILD_SERVICES="mano-base repository"

    - name: pluginmanager
      <<: *python_job_config
      env:
        - SERVICE_NAME=pluginmanager
        - COMPONENT_DIR=src/mano-framework/pluginmanager
        - REQUIRED_MICROSERVICES="broker mongo"
        - BUILD_SERVICES="mano-base pluginmanager"

    - name: flm-base
      <<: *python_job_config
      env:
        - SERVICE_NAME=flm-base
        - COMPONENT_DIR=src/mano-framework/plugins/function-lifecycle-manager-base
        - BUILD_SERVICES="mano-base flm-base"

    - name: klm
      <<: *python_job_config
      script: *docker_compose_build_command # No tests here, they are in flm-base
      env:
        - SERVICE_NAME=kubernetes-lifecycle-manager
        - COMPONENT_DIR=src/mano-framework/plugins/kubernetes-lifecycle-manager
        - BUILD_SERVICES="mano-base flm-base kubernetes-lifecycle-manager"

    - name: olm
      <<: *python_job_config
      script: *docker_compose_build_command # There are no tests :(
      env:
        - SERVICE_NAME=openstack-lifecycle-manager
        - COMPONENT_DIR=src/mano-framework/plugins/openstack-lifecycle-manager
        - BUILD_SERVICES="mano-base openstack-lifecycle-manager"

    - name: placement
      <<: *python_job_config
      script: *docker_compose_build_command # There are no tests :(
      env:
        - SERVICE_NAME=placementplugin
        - COMPONENT_DIR=src/mano-framework/plugins/placement
        - BUILD_SERVICES="mano-base placementplugin"

    - name: slm
      <<: *python_job_config
      env:
        - SERVICE_NAME=service-lifecycle-manager
        - COMPONENT_DIR=src/mano-framework/plugins/service-lifecycle-manager
        - BUILD_SERVICES="mano-base service-lifecycle-manager"

    - name: smr
      <<: *python_job_config
      env:
        - SERVICE_NAME=specific-manager-registry
        - COMPONENT_DIR=src/mano-framework/plugins/specific-manager-registry
        - REQUIRED_MICROSERVICES="broker mongo pluginmanager"
        - BUILD_SERVICES="mano-base specific-manager-registry"

    - name: gatekeeper
      <<: *python_job_config
      env:
        - SERVICE_NAME=gatekeeper
        - COMPONENT_DIR=src/gatekeeper
        - BUILD_SERVICES="mano-base gatekeeper"

    - name: vim-adaptor
      <<: *python_job_config
      env:
        - SERVICE_NAME=vim-adaptor
        - COMPONENT_DIR=src/mano-framework/plugins/vim-adaptor
        - BUILD_SERVICES="mano-base vim-adaptor"

    # Build and push Docker images on each new tag
    - stage: release
      if: tag IS present
      language: generic
      script:
        - *docker_compose_setup_commands
        - export PISHAHANG_VERSION="$TRAVIS_TAG"
        # Build base images first
        - docker-compose build mano-base
        - docker-compose build flm-base
        # Build all images
        - docker-compose build
        # Push all images to Docker registry
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker-compose push

  fast_finish: true
  allow_failures:
    - name: smr # The tests have to be fixed yet
