_docker_compose_setup_commands: &docker_compose_setup_commands
  - ./generate-env.sh 127.0.0.1 localhost
  - if [ ! -z "$REQUIRED_MICROSERVICES" ]; then docker-compose up -d $REQUIRED_MICROSERVICES; fi

_docker_compose_build_command: &docker_compose_build_command cd $TRAVIS_BUILD_DIR && docker-compose build $BUILD_SERVICES

_python_job_config: &python_job_config
  language: python
  python: "3.8"
  cache:
    pip: true
  install:
    - pip install poetry
  before_script: *docker_compose_setup_commands
  script:
    - cd $COMPONENT_DIR && poetry install -v && poetry run pytest
    - *docker_compose_build_command

jobs:
  include:
    - name: manobase
      <<: *python_job_config
      env:
        - SERVICE_NAME=mano-base
        - COMPONENT_DIR=src/mano-framework/base
        - REQUIRED_MICROSERVICES=broker
        - BUILD_SERVICES=mano-base

    - name: pluginmanager
      <<: *python_job_config
      env:
        - SERVICE_NAME=pluginmanager
        - COMPONENT_DIR=src/mano-framework/pluginmanager
        - REQUIRED_MICROSERVICES="broker mongo"
        - BUILD_SERVICES="mano-base pluginmanager"

    - name: klm
      <<: *python_job_config
      script: *docker_compose_build_command # There are no tests :(
      env:
        - SERVICE_NAME=kubernetes-lifecycle-manager
        - COMPONENT_DIR=src/mano-framework/plugins/kubernetes-lifecycle-manager
        - BUILD_SERVICES="mano-base kubernetes-lifecycle-manager"

    - name: olm
      <<: *python_job_config
      script: *docker_compose_build_command # There are no tests :(
      env:
        - SERVICE_NAME=openstack-lifecycle-manager
        - COMPONENT_DIR=src/mano-framework/plugins/openstack-lifecycle-manager
        - BUILD_SERVICES="mano-base openstack-lifecycle-manager"

    - name: placement
      <<: *python_job_config
      script: *docker_compose_build_command # There are no tests :(
      env:
        - SERVICE_NAME=placementplugin
        - COMPONENT_DIR=src/mano-framework/plugins/placement
        - BUILD_SERVICES="mano-base placementplugin"

    - name: slm
      <<: *python_job_config
      env:
        - SERVICE_NAME=servicelifecyclemanagement
        - COMPONENT_DIR=src/mano-framework/plugins/service-lifecycle-management
        - BUILD_SERVICES="mano-base servicelifecyclemanagement"

    - name: specific-manager-registry
      <<: *python_job_config
      env:
        - SERVICE_NAME=specificmanagerregistry
        - COMPONENT_DIR=src/mano-framework/specificmanager/specific-manager-registry
        - REQUIRED_MICROSERVICES=broker
        - BUILD_SERVICES="mano-base specificmanagerregistry"

  fast_finish: true
  allow_failures:
    - name: specific-manager-registry # The tests have to be fixed yet
