# Development docker-compose.yml override
version: "3.3"

services:
  # Influxdb for monitoring
  monitor-influxdb:
    build: ./monitor/influxDB

  # Repositories
  catalogue-repos:
    build: ./son-catalogue-repos

  # MANO framework -------------------------------------------------------------
  # Base
  mano-base:
    image: pishahang/mano-base:${PISHAHANG_VERSION}
    build: ./mano-framework/base

  # Plugin Manager
  pluginmanager:
    build: ./mano-framework/pluginmanager

  # Service Lifecycle Management Plugin
  servicelifecyclemanagement:
    build: ./mano-framework/plugins/service-lifecycle-management

  # Function Lifecycle Management Plugin
  functionlifecyclemanagement:
    build: ./mano-framework/plugins/function-lifecycle-management

  # Specific Manager Registry (SMR)
  specificmanagerregistry:
    build: ./mano-framework/specificmanager/specific-manager-registry

  # Placement Plugin
  placementplugin:
    build: ./mano-framework/plugins/placement

  # Cloud Service Life-cycle Management Plugin
  cloudservicelifecyclemanagement:
    build: ./mano-framework/plugins/cloud-service-lifecycle-management

  # SDN Plugin
  sdn-plugin:
    build: ./mano-framework/plugins/sdn

  # VIM Adaptor
  vim-adaptor:
    build: ./vim-adaptor

  # Monitoring -----------------------------------------------------------------
  # Monitoring Push Gateway
  monitor-pushgateway:
    build: ./monitor/pushgateway

  # Monitoring – Prometheus
  monitor-prometheus:
    build: ./monitor/prometheus

  # Monitoring Manager
  monitor-manager:
    build: ./monitor/manager

  # Monitoring – Probe
  monitor-probe:
    # build: ./monitor/ ?
