# Development docker-compose.yml override
version: "3.3"

services:
  traefik:
    ports:
      - "8080:8080"

  mongo:
    ports:
      - 27017:27017

  redis:
    ports:
      - 6379:6379

  monitor-postgres:
    ports:
      - 5433:5432

  broker:
    ports:
      - 5672:5672
      - 15672:15672

  monitor-influxdb:
    build: ./src/monitor/influxDB
    ports:
      - 8086:8086

  # Repository
  repository:
    build: ./src/repository
    ports:
      - 5000:5000

  # Gatekeeper
  gatekeeper:
    build: ./src/gatekeeper
    ports:
      - "5555:5555"

  # GUI
  gui:
    build: ./src/gui

  # MANO framework -------------------------------------------------------------
  # Base
  mano-base:
    image: pishahang/mano-base:${PISHAHANG_VERSION}
    build:
      context: ./src
      dockerfile: mano-framework/base/Dockerfile

  # FLM base
  flm-base:
    image: pishahang/mano-plugin-flm-base:${PISHAHANG_VERSION}
    build: ./src/mano-framework/plugins/function-lifecycle-manager-base

  # Plugin Manager
  pluginmanager:
    build: ./src/mano-framework/pluginmanager
    ports:
      - "8001:8001"

  # Service Lifecycle Management Plugin
  service-lifecycle-manager:
    build: ./src/mano-framework/plugins/service-lifecycle-manager

  # OpenStack Lifecycle Manager
  openstack-lifecycle-manager:
    build: ./src/mano-framework/plugins/openstack-lifecycle-manager

  # Specific Manager Registry (SMR)
  specific-manager-registry:
    build: ./src/mano-framework/plugins/specific-manager-registry

  # Placement Plugin
  placementplugin:
    build: ./src/mano-framework/plugins/placement

  # Kubernetes Lifecycle Manager
  kubernetes-lifecycle-manager:
    build: ./src/mano-framework/plugins/kubernetes-lifecycle-manager

  # AWS Lifecycle Manager
  aws-lifecycle-manager:
    build: ./src/mano-framework/plugins/aws-lifecycle-manager

  # VIM Adaptor
  vim-adaptor:
    build: ./src/mano-framework/plugins/vim-adaptor

  # Monitoring -----------------------------------------------------------------
  # Monitoring Push Gateway
  monitor-pushgateway:
    build: ./src/monitor/pushgateway
    ports:
      - 9091:9091

  # Monitoring – Prometheus
  monitor-prometheus:
    build: ./src/monitor/prometheus

  # Monitoring Manager
  monitor-manager:
    build: ./src/monitor/manager
    ports:
      - "8000:8000"
      - "8888:8888"

  # Monitoring – Probe
  monitor-probe:
    {}
    # build: ./monitor/ ?
