# Pishahang docker-compose file
version: "3.3"

networks:
  # Network to connect client-facing components to traefik
  web:
    external: false

services:
  # Reverse proxy for GUI and gatekeeper
  traefik:
    image: "traefik:v2.2"
    restart: always
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
    networks:
      - web
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  # MongoDB
  mongo:
    image: mongo
    restart: always
    networks:
      default:
        aliases:
          - son-mongo

  # RedisDB for the gatekeeper
  redis:
    image: redis
    restart: always
    networks:
      default:
        aliases:
          - son-redis

  # PostgreSQL database engine for monitoring
  monitor-postgres:
    image: ntboes/postgres-uuid
    restart: always
    environment:
      POSTGRES_DB: ${MON_DB_NAME}
      POSTGRES_USER: ${MON_DB_USER}
      POSTGRES_PASSWORD: ${MON_DB_PASS}
    command: postgres -p 5433
    networks:
      default:
        aliases:
          - postgsql
          - son-monitor-postgres

  # RabbitMQ
  broker:
    image: rabbitmq:3.6.15-management
    restart: always
    environment:
      RABBITMQ_CONSOLE_LOG: new
    networks:
      default:
        aliases:
          - son-broker

  # Influxdb for monitoring
  monitor-influxdb:
    image: pishahang/monitor-influxdb
    restart: always
    networks:
      default:
        aliases:
          - influxdb
          - influx
          - son-monitor-influxdb

  # Repository
  repository:
    image: pishahang/repository:${PISHAHANG_VERSION}
    restart: always
    depends_on:
      - mongo

  # Gatekeeper
  gatekeeper:
    image: pishahang/gatekeeper:${PISHAHANG_VERSION}
    restart: always
    depends_on:
      - broker
      - mongo
      - redis
    environment:
      INITIAL_USERNAME: ${INITIAL_USERNAME}
      INITIAL_PASSWORD: ${INITIAL_PASSWORD}
    networks:
      - default
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=pishahang_web"
      - "traefik.http.routers.gatekeeper.rule=PathPrefix(`/api`)"
      - "traefik.http.routers.gatekeeper.entrypoints=web"

  # GUI
  gui:
    image: pishahang/gui:${PISHAHANG_VERSION}
    restart: always
    depends_on:
      - gatekeeper
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gui.rule=PathPrefix(`/`)"
      - "traefik.http.routers.gui.entrypoints=web"

  # MANO framework -------------------------------------------------------------
  # Plugin Manager
  pluginmanager:
    image: pishahang/mano-pluginmanager:${PISHAHANG_VERSION}
    restart: always
    depends_on:
      - broker
      - mongo
    environment:
      mongo_host: mongo

  # Service Lifecycle Management Plugin
  service-lifecycle-manager:
    image: pishahang/mano-plugin-service-lifecycle-manager:${PISHAHANG_VERSION}
    restart: always
    depends_on:
      - broker
      - pluginmanager
      - mongo
      - repository
      - monitor-manager
    environment:
      url_monitoring_server: http://monitor-manager:8000/api/v1/

  # OpenStack Lifecycle Manager
  openstack-lifecycle-manager:
    image: pishahang/mano-plugin-openstack-lifecycle-manager:${PISHAHANG_VERSION}
    restart: always
    depends_on:
      - broker
      - pluginmanager
      - repository
      - monitor-manager
    environment:
      url_monitoring_server: http://monitor-manager:8000/api/v1/

  # Specific Manager Registry (SMR)
  specific-manager-registry:
    image: pishahang/mano-plugin-specific-manager-registry:${PISHAHANG_VERSION}
    restart: always
    depends_on:
      - broker
      - pluginmanager
    environment:
      broker_name: broker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  # Placement Plugin
  placementplugin:
    image: pishahang/mano-plugin-placement:${PISHAHANG_VERSION}
    restart: always
    depends_on:
      - broker
      - pluginmanager

  # Kubernetes Lifecycle Manager
  kubernetes-lifecycle-manager:
    image: pishahang/mano-plugin-kubernetes-lifecycle-manager:${PISHAHANG_VERSION}
    restart: always
    depends_on:
      - broker
      - pluginmanager
      - repository

  # AWS Lifecycle Manager
  aws-lifecycle-manager:
    image: pishahang/mano-plugin-aws-lifecycle-manager:${PISHAHANG_VERSION}
    restart: always
    depends_on:
      - broker
      - pluginmanager
      - repository

  # Vim Adaptor
  vim-adaptor:
    image: pishahang/mano-plugin-vim-adaptor:${PISHAHANG_VERSION}
    restart: always
    depends_on:
      - broker
      - mongo
      - pluginmanager

  # Monitoring -----------------------------------------------------------------
  # Monitoring Push Gateway
  monitor-pushgateway:
    image: pishahang/monitor-pushgateway:${PISHAHANG_VERSION}
    restart: always
    networks:
      default:
        aliases:
          - pushgateway
          - son-monitor-pushgateway

  # Monitoring – Prometheus
  monitor-prometheus:
    image: pishahang/monitor-prometheus:${PISHAHANG_VERSION}
    restart: always
    depends_on:
      - broker
    environment:
      RABBIT_URL: broker:5672
      EMAIL_PASS: czBuQHRAX21vbl9zeXNfMTY=
    networks:
      default:
        aliases:
          - prometheus
          - son-monitor-prometheus
    ports:
      - "9090:9090"
      - "9089:9089"
      - "8002:8001"

  # Monitoring Manager
  monitor-manager:
    image: pishahang/monitor-manager:${PISHAHANG_VERSION}
    restart: always
    networks:
      default:
        aliases:
          - son-monitor-manager

  # Monitoring – Probe
  monitor-probe:
    image: sonatanfv/son-monitor-probe
    restart: always
    privileged: true
    depends_on:
      - monitor-pushgateway
    environment:
      NODE_NAME: localhost
      PROM_SRV: http://monitor-pushgateway:9091/metrics
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /:/rootfs:ro
      - /proc:/myhost/proc
    networks:
      default:
        aliases:
          - son-monitor-probe
