# Development docker-compose.yml override
version: "3.3"

services:
  # Influxdb for monitoring
  son-monitor-influxdb:
    build: ./son-monitor/influxDB

  # Repositories
  son-catalogue-repos:
    build: ./son-catalogue-repos

  # MANO framework -------------------------------------------------------------
  # MANO Plug-in Manager
  pluginmanager:
    build:
      context: ./son-mano-framework
      dockerfile: ./son-mano-pluginmanager/Dockerfile

  # MANO Service Life-cycle Management
  servicelifecyclemanagement:
    build:
      context: ./son-mano-framework
      dockerfile: ./plugins/son-mano-service-lifecycle-management/Dockerfile

  # MANO Function Lifecycle Management Plugin
  functionlifecyclemanagement:
    build:
      context: ./son-mano-framework
      dockerfile: ./plugins/son-mano-function-lifecycle-management/Dockerfile

  # MANO Specific Manager Registry (SMR)
  specificmanagerregistry:
    build:
      context: ./son-mano-framework
      dockerfile: ./son-mano-specificmanager/son-mano-specific-manager-registry/Dockerfile

  # MANO Placement Executive Plugin
  placementexecutive:
    build:
      context: ./son-mano-framework
      dockerfile: ./plugins/son-mano-placement-executive/Dockerfile

  # MANO Placement Plugin
  placementplugin:
    build:
      context: ./son-mano-framework
      dockerfile: ./plugins/son-mano-placement/Dockerfile

  # MANO Cloud Service Life-cycle Management (CLM)
  cloudservicelifecyclemanagement:
    build:
      context: ./son-mano-framework
      dockerfile: ./plugins/son-mano-cloud-service-lifecycle-management/Dockerfile

  # MANO SDN
  sdn-plugin:
    build:
      context: ./son-mano-framework
      dockerfile: ./plugins/pish-mano-sdn/Dockerfile

  # VIM Adaptor
  vim-adaptor:
    build: ./vim-adaptor


  # Monitoring -----------------------------------------------------------------
  # Monitoring Push Gateway
  son-monitor-pushgateway:
    build: ./son-monitor/pushgateway

  # Monitoring – Prometheus
  son-monitor-prometheus:
    build: ./son-monitor/prometheus

  # Monitoring Manager
  son-monitor-manager:
    build: ./son-monitor/manager

  # Monitoring – Probe
  son-monitor-probe:
    # build: ./son-monitor/ ?
