# Development docker-compose.yml override
version: "3.3"

services:
  # Influxdb for monitoring
  monitor-influxdb:
    build: ./src/monitor/influxDB

  # Repositories
  catalogue-repos:
    build: ./son-catalogue-repos

  # MANO framework -------------------------------------------------------------
  # Base
  mano-base:
    image: pishahang/mano-base:${PISHAHANG_VERSION}
    build: ./src/mano-framework/base

  # Plugin Manager
  pluginmanager:
    build: ./src/mano-framework/pluginmanager

  # Service Lifecycle Management Plugin
  service-lifecycle-manager:
    build: ./src/mano-framework/plugins/service-lifecycle-manager

  # OpenStack Lifecycle Manager
  openstack-lifecycle-manager:
    build: ./src/mano-framework/plugins/openstack-lifecycle-manager

  # Specific Manager Registry (SMR)
  specific-manager-registry:
    build: ./src/mano-framework/plugins/specific-manager-registry

  # Placement Plugin
  placementplugin:
    build: ./src/mano-framework/plugins/placement

  # Kubernetes Lifecycle Manager
  kubernetes-lifecycle-manager:
    build: ./src/mano-framework/plugins/kubernetes-lifecycle-manager

  # SDN Plugin
  sdn-plugin:
    build: ./src/mano-framework/plugins/sdn

  # Monitoring -----------------------------------------------------------------
  # Monitoring Push Gateway
  monitor-pushgateway:
    build: ./src/monitor/pushgateway

  # Monitoring – Prometheus
  monitor-prometheus:
    build: ./src/monitor/prometheus

  # Monitoring Manager
  monitor-manager:
    build: ./src/monitor/manager

  # Monitoring – Probe
  monitor-probe:
    # build: ./monitor/ ?
