# Development docker-compose.yml override
version: "3.3"

services:
  # Influxdb for monitoring
  monitor-influxdb:
    build: ./monitor/influxDB

  # Repositories
  catalogue-repos:
    build: ./son-catalogue-repos

  # MANO framework -------------------------------------------------------------
  # MANO base
  mano-base:
    image: pishahang/mano-base:${PISHAHANG_VERSION}
    build: ./mano-framework/base

  # MANO Plugin Manager
  pluginmanager:
    build: ./mano-framework/pluginmanager

  # MANO Service Life-cycle Management
  servicelifecyclemanagement:
    build: ./mano-framework/plugins/service-lifecycle-management

  # MANO Function Lifecycle Management Plugin
  functionlifecyclemanagement:
    build: ./mano-framework/plugins/function-lifecycle-management

  # MANO Specific Manager Registry (SMR)
  specificmanagerregistry:
    build: ./mano-framework/specificmanager/specific-manager-registry

  # MANO Placement Executive Plugin
  placementexecutive:
    build: ./mano-framework/plugins/placement-executive

  # MANO Placement Plugin
  placementplugin:
    build: ./mano-framework/plugins/placement

  # MANO Cloud Service Life-cycle Management (CLM)
  cloudservicelifecyclemanagement:
    build: ./mano-framework/plugins/cloud-service-lifecycle-management

  # MANO SDN
  sdn-plugin:
    build: ./mano-framework/plugins/sdn

  # VIM Adaptor
  vim-adaptor:
    build: ./vim-adaptor

  # Monitoring -----------------------------------------------------------------
  # Monitoring Push Gateway
  monitor-pushgateway:
    build: ./monitor/pushgateway

  # Monitoring – Prometheus
  monitor-prometheus:
    build: ./monitor/prometheus

  # Monitoring Manager
  monitor-manager:
    build: ./monitor/manager

  # Monitoring – Probe
  monitor-probe:
    # build: ./monitor/ ?
