# Pishahang docker-compose file
version: "3.3"

networks:
  pishanet:
    external: false

services:
  # PostgreSQL database engine
  postgres:
    image: ntboes/postgres-uuid #sonatanfv/son-postgres
    restart: always
    environment:
      POSTGRES_DB: ${GTK_DB_NAME}
      POSTGRES_USER: ${GTK_DB_USER}
      POSTGRES_PASSWORD: ${GTK_DB_PASS}
    networks:
      pishanet:
        aliases:
          - son-postgres
    ports:
      - 5432:5432

  # MongoDB (used by Monitory)
  mongo:
    image: mongo
    restart: always
    networks:
      pishanet:
        aliases:
          - son-mongo
    ports:
      - 27017:27017

  # RedisDB for the gatekeeper
  redis:
    image: redis
    restart: always
    networks:
      pishanet:
        aliases:
          - son-redis
    ports:
      - 6379:6379

  # PostgreSQL database engine for monitoring
  monitor-postgres:
    image: ntboes/postgres-uuid
    restart: always
    environment:
      POSTGRES_DB: ${MON_DB_NAME}
      POSTGRES_USER: ${MON_DB_USER}
      POSTGRES_PASSWORD: ${MON_DB_PASS}
    command: postgres -p 5433
    networks:
      pishanet:
        aliases:
          - postgsql
          - son-monitor-postgres
    ports:
      - 5433:5432

  # RabbitMQ
  broker:
    image: rabbitmq:3.6.15-management
    restart: always
    environment:
      RABBITMQ_CONSOLE_LOG: new
    networks:
      pishanet:
        aliases:
          - son-broker
    ports:
      - 5672:5672
      - 15672:15672

  # Influxdb for monitoring
  monitor-influxdb:
    image: pishahang/monitor-influxdb
    restart: always
    networks:
      pishanet:
        aliases:
          - influxdb
          - influx
          - son-monitor-influxdb
    ports:
      - 8086:8086

  # Repository
  repository:
    image: pishahang/repository:${PISHAHANG_VERSION}
    restart: always
    depends_on:
      - mongo
    networks:
      - pishanet
    ports:
      - "5000:5000"

  # Gatekeeper
  gatekeeper:
    image: pishahang/gatekeeper:${PISHAHANG_VERSION}
    restart: always
    depends_on:
      - mongo
      - broker
    networks:
      - pishanet
    ports:
      - "5555:5555"

  # GUI
  gui:
    image: pishahang/gui:${PISHAHANG_VERSION}
    restart: always
    depends_on:
      - gatekeeper

  # MANO framework -------------------------------------------------------------
  # Plugin Manager
  pluginmanager:
    image: pishahang/mano-pluginmanager:${PISHAHANG_VERSION}
    restart: always
    depends_on:
      - mongo
      - broker
    environment:
      mongo_host: mongo
    networks:
      - pishanet
    ports:
      - "8001:8001"

  # Service Lifecycle Management Plugin
  service-lifecycle-manager:
    image: pishahang/mano-plugin-service-lifecycle-manager:${PISHAHANG_VERSION}
    restart: always
    depends_on:
      - broker
      - repository
      - monitor-manager
    environment:
      url_monitoring_server: http://monitor-manager:8000/api/v1/
    networks:
      - pishanet

  # OpenStack Lifecycle Manager
  openstack-lifecycle-manager:
    image: pishahang/mano-plugin-openstack-lifecycle-manager:${PISHAHANG_VERSION}
    restart: always
    depends_on:
      - broker
      - repository
      - monitor-manager
    environment:
      url_monitoring_server: http://monitor-manager:8000/api/v1/
    networks:
      - pishanet

  # Specific Manager Registry (SMR)
  specific-manager-registry:
    image: pishahang/mano-plugin-specific-manager-registry:${PISHAHANG_VERSION}
    restart: always
    depends_on:
      - broker
    environment:
      broker_name: broker
    networks:
      - pishanet
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  # Placement Plugin
  placementplugin:
    image: pishahang/mano-plugin-placement:${PISHAHANG_VERSION}
    restart: always
    depends_on:
      - broker
    networks:
      - pishanet

  # Kubernetes Lifecycle Manager
  kubernetes-lifecycle-manager:
    image: pishahang/mano-plugin-kubernetes-lifecycle-manager:${PISHAHANG_VERSION}
    restart: always
    depends_on:
      - broker
      - monitor-manager
      - repository
    networks:
      - pishanet

  # Monitoring -----------------------------------------------------------------
  # Monitoring Push Gateway
  monitor-pushgateway:
    image: pishahang/monitor-pushgateway:${PISHAHANG_VERSION}
    restart: always
    networks:
      pishanet:
        aliases:
          - pushgateway
          - son-monitor-pushgateway
    ports:
      - "9091:9091"

  # Monitoring – Prometheus
  monitor-prometheus:
    image: pishahang/monitor-prometheus:${PISHAHANG_VERSION}
    restart: always
    depends_on:
      - broker
    environment:
      RABBIT_URL: broker:5672
      EMAIL_PASS: czBuQHRAX21vbl9zeXNfMTY=
    networks:
      pishanet:
        aliases:
          - prometheus
          - son-monitor-prometheus
    ports:
      - "9090:9090"
      - "9089:9089"
      - "8002:8001"

  # Monitoring Manager
  monitor-manager:
    image: pishahang/monitor-manager:${PISHAHANG_VERSION}
    restart: always
    networks:
      pishanet:
        aliases:
          - son-monitor-manager
    ports:
      - "8000:8000"
      - "8888:8888"

  # Monitoring – Probe
  monitor-probe:
    image: sonatanfv/son-monitor-probe:${SONATA_VERSION}
    restart: always
    privileged: true
    depends_on:
      - monitor-pushgateway
    environment:
      NODE_NAME: ${HOSTNAME}
      PROM_SRV: http://monitor-pushgateway:9091/metrics
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /:/rootfs:ro
      - /proc:/myhost/proc
    networks:
      pishanet:
        aliases:
          - son-monitor-probe
