databases:
  mongo: mongodb://localhost:27017/gatekeeper
  redis: redis://localhost:6379/gatekeeper

internalApis:
  pluginmanager: http://localhost:8001/api/plugins

broker:
  host: amqp://guest:guest@localhost:5672/%2F
