databases:
  mongo: mongodb://son-mongo/gatekeeper
  redis: redis://redis:6379/gatekeeper

keycloak:
  url: http://son-keycloak:5601/auth/
  realmName: sonata
  clientId: adapter

connexion:
  swagger_ui_config:
    showExtensions: true