databases:
  mongo: mongodb://son-mongo/gatekeeper
  redis: redis://redis:6379/gatekeeper

initialUserData:
  username: pishahang
  password: "1234"
  isAdmin: true

jwt:
  accessTokenLifetime: 900 # 15 min
  refreshTokenLifetime: 604800 # 7 days

connexion:
  swagger_ui_config:
    showExtensions: true
