databases:
  mongo: mongodb://mongo/gatekeeper
  redis: redis://redis:6379/gatekeeper

broker:
  host: amqp://guest:guest@broker:5672/%2F

internalApis:
  pluginmanager: http://mano-pluginmanager:8001/api/plugins
