apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod
spec:
  containers:
    - name: cuda-container
      image: pgscramble/transcoder-cn:0.9
      resources:
        limits:
          nvidia.com/gpu: 1 # requesting 2 GPUs
