openapi: 3.0.0

info:
  version: 1.0.0
  title: Pishahang Gatekeeper Config API
  description: The definition of the Gatekeeper's Pishahang-internal configuration API

servers:
  - url: /config

tags:
  - name: Keycloak
    description: Keycloak-related settings

paths:
  /keycloak/client-secret:
    put:
      tags:
        - Keycloak
      summary: Set the Keycloak client secret
      description:
        Sets the Keycloak client secret used to authenticate the gatekeeper at the Keycloak API.
        This endpoint should be used by the Keycloak container on its initialization.
      operationId: gatekeeper.api.config.setKeycloakClientSecret
      requestBody:
        description: The new Keycloak client secret
        required: true
        content:
          text/plain; charset=utf-8:
            schema:
              type: string
              example: 42601cc6-9cd5-463a-b78f-b6e21d4ee15e
      responses:
        "200":
          $ref: "#/components/responses/SuccessfullySet"
        "400":
          $ref: "#/components/responses/Error400"
        "500":
          $ref: "#/components/responses/Error500"

components:
  schemas:
    Message:
      required:
        - status
        - detail
      properties:
        status:
          type: number
        detail:
          type: string
  responses:
    SuccessfullySet:
      description: The value was successfully set.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Message"
    Error400:
      description: The request is invalid.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Message"
    Error404:
      description: The requested resource could not be found.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Message"
    Error500:
      description: An unexpected error occurred.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Message"
